use std::process::Command;
use std::{env, fs};

fn intent() -> Command {
    Command::new(env!("CARGO_BIN_EXE_intent"))
}

fn valid_intent(name: &str) -> std::path::PathBuf {
    let path = env::temp_dir().join(format!("intent-{name}-{}.yaml", std::process::id()));
    fs::write(
        &path,
        r#"
version: 1
application:
  name: demo
  executable: /usr/bin/demo
"#,
    )
    .expect("test intent file should be written");
    path
}

#[test]
fn starts_and_prints_help() {
    let output = intent().output().expect("intent command should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    assert!(stdout.contains("intent validate <intent.yaml>"));
    assert!(stdout.contains("intent build <intent.yaml> --target selinux|apparmor|all"));
    assert!(stdout.contains("intent observe --source <audit.log> --format selinux|apparmor"));
    assert!(stdout.contains("intent explain <intent.yaml>"));
}

#[test]
fn recognizes_validate() {
    let path = valid_intent("validate");
    let output = intent()
        .arg("validate")
        .arg(&path)
        .output()
        .expect("intent validate should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    assert!(stdout.contains("Validated"));
    assert!(stdout.contains("demo"));
}

#[test]
fn recognizes_build_targets() {
    let path = valid_intent("build");
    for target in ["selinux", "apparmor", "all"] {
        let output = intent()
            .arg("build")
            .arg(&path)
            .args(["--target", target])
            .output()
            .expect("intent build should run");

        assert!(
            output.status.success(),
            "target {target} should be accepted"
        );
        let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
        match target {
            "selinux" => {
                assert!(stdout.starts_with("# Generated by Intent. Do not edit directly."));
                assert!(stdout.contains("policy_module(demo, 1.0)"));
                assert!(stdout.contains("type demo_t;"));
            }
            "apparmor" => {
                assert!(stdout.starts_with("# Generated by Intent. Do not edit directly."));
                assert!(stdout.contains("profile demo /usr/bin/demo {"));
            }
            "all" => {
                assert!(stdout.contains("policy_module(demo, 1.0)"));
                assert!(stdout.contains("profile demo /usr/bin/demo {"));
            }
            _ => unreachable!(),
        }
    }
}

#[test]
fn build_apparmor_can_write_to_output_directory() {
    let path = valid_intent("build-output");
    let output_dir = env::temp_dir().join(format!("intent-build-output-{}", std::process::id()));
    let output = intent()
        .arg("build")
        .arg(&path)
        .args(["--target", "apparmor", "--output"])
        .arg(&output_dir)
        .output()
        .expect("intent build should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    let profile_path = output_dir.join("demo.apparmor");
    assert!(stdout.contains(&format!("Wrote {}", profile_path.display())));

    let profile = fs::read_to_string(profile_path).expect("profile should be written");
    assert!(profile.contains("profile demo /usr/bin/demo {"));
}

#[test]
fn build_selinux_can_write_policy_and_file_contexts_to_output_directory() {
    let path = valid_intent("build-selinux-output");
    let output_dir = env::temp_dir().join(format!(
        "intent-selinux-build-output-{}",
        std::process::id()
    ));
    let output = intent()
        .arg("build")
        .arg(&path)
        .args(["--target", "selinux", "--output"])
        .arg(&output_dir)
        .output()
        .expect("intent build should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    let module_path = output_dir.join("demo.te");
    let contexts_path = output_dir.join("demo.fc");
    assert!(stdout.contains(&format!("Wrote {}", module_path.display())));
    assert!(stdout.contains(&format!("Wrote {}", contexts_path.display())));

    let module = fs::read_to_string(module_path).expect("module should be written");
    assert!(module.contains("policy_module(demo, 1.0)"));

    let contexts = fs::read_to_string(contexts_path).expect("file contexts should be written");
    assert!(contexts.contains("/usr/bin/demo -- gen_context(system_u:object_r:demo_exec_t,s0)"));
}

#[test]
fn recognizes_observe_formats() {
    for format in ["selinux", "apparmor"] {
        let output = intent()
            .args(["observe", "--source", "audit.log", "--format", format])
            .output()
            .expect("intent observe should run");

        assert!(
            output.status.success(),
            "format {format} should be accepted"
        );
        let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
        assert!(stdout.contains("Observe placeholder"));
        assert!(stdout.contains(format));
    }
}

#[test]
fn recognizes_explain() {
    let path = valid_intent("explain");
    let output = intent()
        .arg("explain")
        .arg(&path)
        .output()
        .expect("intent explain should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    assert!(stdout.contains("Intent IR"));
    assert!(stdout.contains("Application:"));
    assert!(stdout.contains("demo"));
    assert!(stdout.contains("executable: /usr/bin/demo"));
}

#[test]
fn validate_rejects_invalid_config() {
    let path = env::temp_dir().join(format!("intent-invalid-{}.yaml", std::process::id()));
    fs::write(
        &path,
        r#"
version: 1
application:
  name: ""
  executable: demo
"#,
    )
    .expect("test intent file should be written");

    let output = intent()
        .arg("validate")
        .arg(&path)
        .output()
        .expect("intent validate should run");

    assert!(!output.status.success());
    let stderr = String::from_utf8(output.stderr).expect("stderr should be utf-8");
    assert!(stderr.contains("application.name must not be empty"));
    assert!(stderr.contains("application.executable must be an absolute path"));
}

#[test]
fn validate_allows_warnings_by_default() {
    let path = env::temp_dir().join(format!("intent-warning-{}.yaml", std::process::id()));
    fs::write(
        &path,
        r#"
version: 1
application:
  name: demo
  executable: /usr/bin/demo
storage:
  config:
    - path: /etc
      access: read
"#,
    )
    .expect("test intent file should be written");

    let output = intent()
        .arg("validate")
        .arg(&path)
        .output()
        .expect("intent validate should run");

    assert!(output.status.success());
    let stderr = String::from_utf8(output.stderr).expect("stderr should be utf-8");
    assert!(stderr.contains("warning: storage.config[0].path is very broad"));
}

#[test]
fn validate_can_deny_warnings() {
    let path = env::temp_dir().join(format!("intent-deny-warning-{}.yaml", std::process::id()));
    fs::write(
        &path,
        r#"
version: 1
application:
  name: demo
  executable: /usr/bin/demo
storage:
  config:
    - path: /etc
      access: read
"#,
    )
    .expect("test intent file should be written");

    let output = intent()
        .arg("validate")
        .arg(&path)
        .arg("--deny-warnings")
        .output()
        .expect("intent validate should run");

    assert!(!output.status.success());
    let stderr = String::from_utf8(output.stderr).expect("stderr should be utf-8");
    assert!(stderr.contains("warning: storage.config[0].path is very broad"));
}

#[test]
fn rejects_unknown_command() {
    let output = intent()
        .arg("unknown")
        .output()
        .expect("intent unknown should run");

    assert!(!output.status.success());
    let stderr = String::from_utf8(output.stderr).expect("stderr should be utf-8");
    assert!(stderr.contains("unknown command 'unknown'"));
}
