use std::io::Write;
use std::process::{Command, Stdio};
use std::{env, fs};

fn intent() -> Command {
    Command::new(env!("CARGO_BIN_EXE_intent"))
}

fn valid_intent(name: &str) -> std::path::PathBuf {
    let path = env::temp_dir().join(format!("intent-{name}-{}.yaml", std::process::id()));
    fs::write(
        &path,
        r#"
version: 1
application:
  name: demo
  executable: /usr/bin/demo
"#,
    )
    .expect("test intent file should be written");
    path
}

#[test]
fn starts_and_prints_help() {
    let output = intent().output().expect("intent command should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    assert!(stdout.contains("intent validate <intent.yaml>"));
    assert!(stdout.contains("intent build <intent.yaml> --target selinux|apparmor|systemd|all"));
    assert!(stdout
        .contains("intent observe --source <audit.log> --format selinux|apparmor [--interactive]"));
    assert!(stdout.contains("intent import <policy-file> --format selinux|apparmor"));
    assert!(stdout.contains("intent explain <intent.yaml>"));
    assert!(stdout.contains("intent schema [--format markdown|json-schema]"));
}

#[test]
fn recognizes_validate() {
    let path = valid_intent("validate");
    let output = intent()
        .arg("validate")
        .arg(&path)
        .output()
        .expect("intent validate should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    assert!(stdout.contains("Validated"));
    assert!(stdout.contains("demo"));
}

#[test]
fn recognizes_build_targets() {
    let path = valid_intent("build");
    for target in ["selinux", "apparmor", "systemd", "all"] {
        let output = intent()
            .arg("build")
            .arg(&path)
            .args(["--target", target])
            .output()
            .expect("intent build should run");

        assert!(
            output.status.success(),
            "target {target} should be accepted"
        );
        let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
        match target {
            "selinux" => {
                assert!(stdout.starts_with("# Generated by Intent. Do not edit directly."));
                assert!(stdout.contains("policy_module(demo, 1.0)"));
                assert!(stdout.contains("type demo_t;"));
            }
            "apparmor" => {
                assert!(stdout.starts_with("# Generated by Intent. Do not edit directly."));
                assert!(stdout.contains("profile demo /usr/bin/demo {"));
            }
            "systemd" => {
                assert!(stdout.starts_with("# Generated by Intent. Do not edit directly."));
                assert!(stdout.contains("[Service]"));
                assert!(stdout.contains("NoNewPrivileges=yes"));
                assert!(stdout.contains("ProtectSystem=strict"));
            }
            "all" => {
                assert!(stdout.contains("policy_module(demo, 1.0)"));
                assert!(stdout.contains("profile demo /usr/bin/demo {"));
                assert!(stdout.contains("[Service]"));
            }
            _ => unreachable!(),
        }
    }
}

#[test]
fn build_apparmor_can_write_to_output_directory() {
    let path = valid_intent("build-output");
    let output_dir = env::temp_dir().join(format!("intent-build-output-{}", std::process::id()));
    let output = intent()
        .arg("build")
        .arg(&path)
        .args(["--target", "apparmor", "--output"])
        .arg(&output_dir)
        .output()
        .expect("intent build should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    let profile_path = output_dir.join("demo.apparmor");
    assert!(stdout.contains(&format!("Wrote {}", profile_path.display())));

    let profile = fs::read_to_string(profile_path).expect("profile should be written");
    assert!(profile.contains("profile demo /usr/bin/demo {"));
}

#[test]
fn build_systemd_can_write_dropin_to_output_directory() {
    let path = valid_intent("build-systemd-output");
    let output_dir = env::temp_dir().join(format!(
        "intent-systemd-build-output-{}",
        std::process::id()
    ));
    let output = intent()
        .arg("build")
        .arg(&path)
        .args(["--target", "systemd", "--output"])
        .arg(&output_dir)
        .output()
        .expect("intent build should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    let dropin_path = output_dir.join("10-intent-hardening.conf");
    assert!(stdout.contains(&format!("Wrote {}", dropin_path.display())));

    let dropin = fs::read_to_string(dropin_path).expect("drop-in should be written");
    assert!(dropin.contains("[Service]"));
    assert!(dropin.contains("NoNewPrivileges=yes"));
}

#[test]
fn build_selinux_can_write_policy_and_file_contexts_to_output_directory() {
    let path = valid_intent("build-selinux-output");
    let output_dir = env::temp_dir().join(format!(
        "intent-selinux-build-output-{}",
        std::process::id()
    ));
    let output = intent()
        .arg("build")
        .arg(&path)
        .args(["--target", "selinux", "--output"])
        .arg(&output_dir)
        .output()
        .expect("intent build should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    let module_path = output_dir.join("demo.te");
    let contexts_path = output_dir.join("demo.fc");
    assert!(stdout.contains(&format!("Wrote {}", module_path.display())));
    assert!(stdout.contains(&format!("Wrote {}", contexts_path.display())));

    let module = fs::read_to_string(module_path).expect("module should be written");
    assert!(module.contains("policy_module(demo, 1.0)"));

    let contexts = fs::read_to_string(contexts_path).expect("file contexts should be written");
    assert!(contexts.contains("/usr/bin/demo -- gen_context(system_u:object_r:demo_exec_t,s0)"));
}

#[test]
fn recognizes_observe_formats() {
    let output = intent()
        .args([
            "observe",
            "--source",
            "tests/fixtures/selinux_audit.log",
            "--format",
            "selinux",
        ])
        .output()
        .expect("intent observe should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    assert!(stdout.contains("Suggestion 1 of"));
    assert!(stdout.contains("What was denied:"));
    assert!(stdout.contains("process: himmelblaud"));
    assert!(stdout.contains("path: /var/cache/himmelblaud/tokens.db"));
    assert!(stdout.contains("persistent cache storage"));
    assert!(stdout.contains("storage:\n    cache:\n      - path: /var/cache/himmelblaud"));

    let output = intent()
        .args([
            "observe",
            "--source",
            "tests/fixtures/apparmor_audit.log",
            "--format",
            "apparmor",
        ])
        .output()
        .expect("intent observe should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    assert!(stdout.contains("Suggestion 1 of"));
    assert!(stdout.contains("What was denied:"));
    assert!(stdout.contains("profile: himmelblaud"));
    assert!(stdout.contains("operation: open"));
    assert!(stdout.contains("requested_mask: r"));
    assert!(stdout.contains("denied_mask: r"));
    assert!(stdout.contains("name: /etc/himmelblaud/config.yaml"));
    assert!(stdout.contains("persistent config storage"));
    assert!(stdout.contains("persistent cache storage"));
    assert!(stdout.contains("persistent state storage"));
    assert!(stdout.contains("persistent runtime storage"));
    assert!(stdout.contains("network:\n    outbound:"));
    assert!(stdout.contains("ipc:\n    unix_sockets:"));
    assert!(stdout.contains("peer_profile: unconfined"));
}

#[test]
fn imports_selinux_policy_to_valid_intent_yaml() {
    let output = intent()
        .args([
            "import",
            "tests/fixtures/import_realworld_selinux.te",
            "--format",
            "selinux",
        ])
        .output()
        .expect("intent import selinux should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    assert!(stdout.contains("application:\n  name: himmelblaud"));
    assert!(stdout.contains("executable: /usr/bin/himmelblaud"));
    assert!(stdout.contains("storage:"));
    assert!(stdout.contains("path: /var/cache/private/himmelblaud"));
    assert!(stdout.contains("access: read-write"));
    assert!(stdout.contains("capabilities:\n- net-bind-service\n- sys-ptrace"));
    assert!(stdout.contains("extensions:\n  selinux:"));
    assert!(stdout.contains("permissive himmelblaud_t;"));
    assert!(stdout.contains("file_contexts:"));

    let stderr = String::from_utf8(output.stderr).expect("stderr should be utf-8");
    assert!(stderr.contains("warning: preserved"));

    let imported_path =
        env::temp_dir().join(format!("intent-import-selinux-{}.yaml", std::process::id()));
    fs::write(&imported_path, stdout).expect("imported intent should be written");

    let validate = intent()
        .arg("validate")
        .arg(&imported_path)
        .output()
        .expect("imported intent should validate");
    assert!(validate.status.success());

    let build = intent()
        .arg("build")
        .arg(&imported_path)
        .args(["--target", "selinux"])
        .output()
        .expect("imported intent should build");
    assert!(build.status.success());
    let rebuilt = String::from_utf8(build.stdout).expect("stdout should be utf-8");
    assert!(rebuilt.contains("allow himmelblaud_t self:capability sys_ptrace;"));
}

#[test]
fn imports_apparmor_profile_to_valid_intent_yaml() {
    let output = intent()
        .args([
            "import",
            "tests/fixtures/import_realworld.apparmor",
            "--format",
            "apparmor",
        ])
        .output()
        .expect("intent import apparmor should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    assert!(stdout.contains("application:\n  name: demo-service"));
    assert!(stdout.contains("executable: /usr/bin/demo-service"));
    assert!(stdout.contains("path: /etc/demo-service"));
    assert!(stdout.contains("path: /run/demo-service/control.sock"));
    assert!(stdout.contains("mode: server"));
    assert!(stdout.contains("org.example.DemoService"));
    assert!(stdout.contains("capabilities:\n- net-bind-service"));
    assert!(stdout.contains("ptrace read peer=unconfined,"));

    let imported_path = env::temp_dir().join(format!(
        "intent-import-apparmor-{}.yaml",
        std::process::id()
    ));
    fs::write(&imported_path, stdout).expect("imported intent should be written");

    let validate = intent()
        .arg("validate")
        .arg(&imported_path)
        .output()
        .expect("imported intent should validate");
    assert!(validate.status.success());

    let build = intent()
        .arg("build")
        .arg(&imported_path)
        .args(["--target", "apparmor"])
        .output()
        .expect("imported intent should build");
    assert!(build.status.success());
    let rebuilt = String::from_utf8(build.stdout).expect("stdout should be utf-8");
    assert!(rebuilt.contains("ptrace read peer=unconfined,"));
}

#[test]
fn interactive_observe_writes_accepted_suggestions_file() {
    let review_dir = env::temp_dir().join(format!("intent-review-{}", std::process::id()));
    fs::create_dir_all(&review_dir).expect("review dir should be created");
    let source =
        fs::canonicalize("tests/fixtures/selinux_audit.log").expect("fixture path should resolve");

    let mut child = intent()
        .current_dir(&review_dir)
        .arg("observe")
        .arg("--source")
        .arg(source)
        .args(["--format", "selinux", "--interactive"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .expect("interactive observe should start");

    child
        .stdin
        .as_mut()
        .expect("stdin should be piped")
        .write_all(b"a\nr\nr\nr\nr\n")
        .expect("choices should be written");

    let output = child
        .wait_with_output()
        .expect("interactive observe should finish");
    assert!(output.status.success());

    let suggestions_path = review_dir.join("intent.suggestions.yaml");
    let suggestions = fs::read_to_string(suggestions_path).expect("suggestions should be written");
    assert!(suggestions.contains("storage:"));
    assert!(suggestions.contains("/var/cache/himmelblaud"));
}

#[test]
fn recognizes_explain() {
    let path = valid_intent("explain");
    let output = intent()
        .arg("explain")
        .arg(&path)
        .output()
        .expect("intent explain should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    assert!(stdout.contains("Intent IR"));
    assert!(stdout.contains("Application:"));
    assert!(stdout.contains("demo"));
    assert!(stdout.contains("executable: /usr/bin/demo"));
}

#[test]
fn recognizes_schema_markdown() {
    let output = intent()
        .arg("schema")
        .output()
        .expect("intent schema should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    assert!(stdout.contains("# intent.yaml"));
    assert!(stdout.contains("application.executable"));
    assert!(stdout.contains("SELinux:"));
    assert!(stdout.contains("AppArmor:"));

    let output = intent()
        .args(["schema", "--format", "markdown"])
        .output()
        .expect("intent schema markdown should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    assert!(stdout.contains("## Fields"));
    assert!(stdout.contains("Validation Summary"));
}

#[test]
fn recognizes_schema_json_schema() {
    let output = intent()
        .args(["schema", "--format", "json-schema"])
        .output()
        .expect("intent schema json-schema should run");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout should be utf-8");
    assert!(stdout.contains("\"$schema\": \"https://json-schema.org/draft/2020-12/schema\""));
    assert!(stdout.contains("\"additionalProperties\": false"));
    assert!(stdout.contains("\"application\""));
    assert!(stdout.contains("\"runtimeStoragePath\""));
}

#[test]
fn validate_rejects_invalid_config() {
    let path = env::temp_dir().join(format!("intent-invalid-{}.yaml", std::process::id()));
    fs::write(
        &path,
        r#"
version: 1
application:
  name: ""
  executable: demo
"#,
    )
    .expect("test intent file should be written");

    let output = intent()
        .arg("validate")
        .arg(&path)
        .output()
        .expect("intent validate should run");

    assert!(!output.status.success());
    let stderr = String::from_utf8(output.stderr).expect("stderr should be utf-8");
    assert!(stderr.contains("application.name must not be empty"));
    assert!(stderr.contains("application.executable must be an absolute path"));
}

#[test]
fn validate_allows_warnings_by_default() {
    let path = env::temp_dir().join(format!("intent-warning-{}.yaml", std::process::id()));
    fs::write(
        &path,
        r#"
version: 1
application:
  name: demo
  executable: /usr/bin/demo
storage:
  config:
    - path: /etc
      access: read
"#,
    )
    .expect("test intent file should be written");

    let output = intent()
        .arg("validate")
        .arg(&path)
        .output()
        .expect("intent validate should run");

    assert!(output.status.success());
    let stderr = String::from_utf8(output.stderr).expect("stderr should be utf-8");
    assert!(stderr.contains("warning: storage.config[0].path is very broad"));
}

#[test]
fn validate_can_deny_warnings() {
    let path = env::temp_dir().join(format!("intent-deny-warning-{}.yaml", std::process::id()));
    fs::write(
        &path,
        r#"
version: 1
application:
  name: demo
  executable: /usr/bin/demo
storage:
  config:
    - path: /etc
      access: read
"#,
    )
    .expect("test intent file should be written");

    let output = intent()
        .arg("validate")
        .arg(&path)
        .arg("--deny-warnings")
        .output()
        .expect("intent validate should run");

    assert!(!output.status.success());
    let stderr = String::from_utf8(output.stderr).expect("stderr should be utf-8");
    assert!(stderr.contains("warning: storage.config[0].path is very broad"));
}

#[test]
fn rejects_unknown_command() {
    let output = intent()
        .arg("unknown")
        .output()
        .expect("intent unknown should run");

    assert!(!output.status.success());
    let stderr = String::from_utf8(output.stderr).expect("stderr should be utf-8");
    assert!(stderr.contains("unknown command 'unknown'"));
}
