//! AppArmor profile generation.

use crate::schema::{
    IntentDocument, NetworkProtocol, StorageAccess, StoragePath, UnixSocket, UnixSocketMode,
};

/// Generate an AppArmor profile from an Intent document.
pub fn compile(document: &IntentDocument) -> String {
    let mut profile = String::new();

    push_line(&mut profile, "# Generated by Intent. Do not edit directly.");
    push_line(
        &mut profile,
        "# Edit intent.yaml and regenerate this profile.",
    );
    push_line(&mut profile, "#include <tunables/global>");
    push_line(&mut profile, "");
    push_line(
        &mut profile,
        &format!(
            "profile {} {} {{",
            profile_name(&document.application.name),
            apparmor_path(&document.application.executable)
        ),
    );
    push_line(
        &mut profile,
        "  # application.executable: profile attachment and executable read access.",
    );
    push_line(
        &mut profile,
        &format!("  {} r,", apparmor_path(&document.application.executable)),
    );

    push_storage_rules(&mut profile, "storage.config", &document.storage.config);
    push_storage_rules(&mut profile, "storage.cache", &document.storage.cache);
    push_storage_rules(&mut profile, "storage.state", &document.storage.state);
    push_storage_rules(&mut profile, "storage.runtime", &document.storage.runtime);
    push_network_rules(&mut profile, document);
    push_unix_socket_rules(&mut profile, &document.ipc.unix_sockets);
    push_dbus_rules(&mut profile, document);
    push_capability_rules(&mut profile, document);

    push_line(&mut profile, "}");

    profile
}

/// Return the default file name for a generated AppArmor profile.
pub fn profile_file_name(document: &IntentDocument) -> String {
    format!("{}.apparmor", profile_name(&document.application.name))
}

fn push_storage_rules(profile: &mut String, field: &str, paths: &[StoragePath]) {
    for (index, entry) in paths.iter().enumerate() {
        let permissions = match entry.access {
            StorageAccess::Read => "r",
            StorageAccess::ReadWrite => "rwk",
        };
        let access = match entry.access {
            StorageAccess::Read => "read",
            StorageAccess::ReadWrite => "read-write",
        };
        let path = trim_trailing_slashes(&entry.path);

        push_line(profile, "");
        push_line(
            profile,
            &format!("  # {field}[{index}]: {} access to {}.", access, entry.path),
        );
        push_line(
            profile,
            &format!("  {} {permissions},", apparmor_path(&path)),
        );
        push_line(
            profile,
            &format!("  {}/** {permissions},", apparmor_path(&path)),
        );
    }
}

fn push_network_rules(profile: &mut String, document: &IntentDocument) {
    for (index, outbound) in document.network.outbound.iter().enumerate() {
        push_line(profile, "");
        push_line(
            profile,
            &format!(
                "  # network.outbound[{index}]: outbound {} connection to {}{}.",
                protocol_name(outbound.protocol),
                outbound.to,
                outbound
                    .port
                    .map(|port| format!(":{port}"))
                    .unwrap_or_default()
            ),
        );

        match outbound.protocol {
            NetworkProtocol::Http | NetworkProtocol::Https | NetworkProtocol::Tcp => {
                push_line(profile, "  network inet stream,");
                push_line(profile, "  network inet6 stream,");
            }
            NetworkProtocol::Udp => {
                push_line(profile, "  network inet dgram,");
                push_line(profile, "  network inet6 dgram,");
            }
        }
    }
}

fn push_unix_socket_rules(profile: &mut String, sockets: &[UnixSocket]) {
    for (index, socket) in sockets.iter().enumerate() {
        push_line(profile, "");
        match socket.mode {
            UnixSocketMode::Server => {
                push_line(
                    profile,
                    &format!(
                        "  # ipc.unix_sockets[{index}]: create and use server socket {}.",
                        socket.path
                    ),
                );
                push_line(
                    profile,
                    &format!(
                        "  unix (create, bind, listen, accept, send, receive) type=stream addr={},",
                        quoted(&socket.path)
                    ),
                );
            }
            UnixSocketMode::Client => {
                push_line(
                    profile,
                    &format!(
                        "  # ipc.unix_sockets[{index}]: connect to client socket {}.",
                        socket.path
                    ),
                );
                push_line(
                    profile,
                    &format!(
                        "  unix (connect, send, receive) type=stream peer=(addr={}),",
                        quoted(&socket.path)
                    ),
                );
            }
        }
        push_line(profile, &format!("  {} rw,", apparmor_path(&socket.path)));
    }
}

fn push_dbus_rules(profile: &mut String, document: &IntentDocument) {
    for (index, name) in document.ipc.dbus.system.owns.iter().enumerate() {
        push_line(profile, "");
        push_line(
            profile,
            &format!("  # ipc.dbus.system.owns[{index}]: own system bus name {name}."),
        );
        push_line(
            profile,
            &format!("  dbus bind bus=system name={},", quoted(name)),
        );
    }

    for (index, name) in document.ipc.dbus.system.talks_to.iter().enumerate() {
        push_line(profile, "");
        push_line(
            profile,
            &format!("  # ipc.dbus.system.talks_to[{index}]: talk to system bus service {name}."),
        );
        push_line(
            profile,
            &format!("  dbus send bus=system peer=(name={}),", quoted(name)),
        );
        push_line(
            profile,
            &format!("  dbus receive bus=system peer=(name={}),", quoted(name)),
        );
    }
}

fn push_capability_rules(profile: &mut String, document: &IntentDocument) {
    for (index, capability) in document.capabilities.iter().enumerate() {
        push_line(profile, "");
        push_line(
            profile,
            &format!("  # capabilities[{index}]: Linux capability {capability}."),
        );
        push_line(
            profile,
            &format!("  capability {},", capability.replace('-', "_")),
        );
    }
}

fn profile_name(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || matches!(ch, '_' | '-' | '.') {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn protocol_name(protocol: NetworkProtocol) -> &'static str {
    match protocol {
        NetworkProtocol::Http => "http",
        NetworkProtocol::Https => "https",
        NetworkProtocol::Tcp => "tcp",
        NetworkProtocol::Udp => "udp",
    }
}

fn apparmor_path(path: &str) -> String {
    if path
        .chars()
        .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '/' | '.' | '_' | '-' | '*'))
    {
        path.to_string()
    } else {
        quoted(path)
    }
}

fn quoted(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn trim_trailing_slashes(path: &str) -> String {
    if path == "/" {
        path.to_string()
    } else {
        path.trim_end_matches('/').to_string()
    }
}

fn push_line(buffer: &mut String, line: &str) {
    buffer.push_str(line);
    buffer.push('\n');
}
