//! AppArmor profile generation.

use crate::ir::{
    NetworkProtocolNeed, PathAccess, PathNeed, PathPurpose, PolicyIr, UnixSocketNeed,
    UnixSocketRole,
};

/// Generate an AppArmor profile from normalized policy intent.
pub fn compile(ir: &PolicyIr) -> String {
    let mut profile = String::new();

    push_line(&mut profile, "# Generated by Intent. Do not edit directly.");
    push_line(
        &mut profile,
        "# Edit intent.yaml and regenerate this profile.",
    );
    push_line(&mut profile, "#include <tunables/global>");
    push_line(&mut profile, "");
    push_line(
        &mut profile,
        &format!(
            "profile {} {} {{",
            profile_name(&ir.application.name),
            apparmor_path(&ir.application.executable)
        ),
    );
    push_line(
        &mut profile,
        "  # application.executable: profile attachment and executable read access.",
    );
    push_line(
        &mut profile,
        &format!("  {} r,", apparmor_path(&ir.application.executable)),
    );

    push_storage_rules(&mut profile, &storage_paths(ir, PathPurpose::Config));
    push_storage_rules(&mut profile, &storage_paths(ir, PathPurpose::Cache));
    push_storage_rules(&mut profile, &storage_paths(ir, PathPurpose::State));
    push_storage_rules(&mut profile, &storage_paths(ir, PathPurpose::Runtime));
    push_network_rules(&mut profile, &ir.outbound_network);
    push_unix_socket_rules(&mut profile, &ir.unix_sockets);
    push_dbus_rules(&mut profile, ir);
    push_capability_rules(&mut profile, ir);
    push_manual_rules(&mut profile, &ir.manual_extensions.apparmor_rules);

    push_line(&mut profile, "}");

    profile
}

/// Return the default file name for a generated AppArmor profile.
pub fn profile_file_name(ir: &PolicyIr) -> String {
    format!("{}.apparmor", profile_name(&ir.application.name))
}

fn push_storage_rules(profile: &mut String, paths: &[&PathNeed]) {
    for (index, entry) in paths.iter().enumerate() {
        let permissions = match entry.access {
            PathAccess::Read => "r",
            PathAccess::ReadWrite => "rwk",
        };
        let path = trim_trailing_slashes(&entry.path);

        push_line(profile, "");
        push_line(
            profile,
            &format!(
                "  # {} paths[{index}]: {} access to {}.",
                entry.purpose, entry.access, entry.path
            ),
        );
        push_line(
            profile,
            &format!("  {} {permissions},", apparmor_path(&path)),
        );
        push_line(
            profile,
            &format!("  {}/** {permissions},", apparmor_path(&path)),
        );
    }
}

fn push_network_rules(profile: &mut String, outbound: &[crate::ir::OutboundNetworkNeed]) {
    for (index, outbound) in outbound.iter().enumerate() {
        push_line(profile, "");
        push_line(
            profile,
            &format!(
                "  # outbound network[{index}]: outbound {} connection to {}:{}.",
                protocol_name(outbound.protocol),
                outbound.to,
                outbound.port
            ),
        );

        match outbound.protocol {
            NetworkProtocolNeed::Http | NetworkProtocolNeed::Https | NetworkProtocolNeed::Tcp => {
                push_line(profile, "  network inet stream,");
                push_line(profile, "  network inet6 stream,");
            }
            NetworkProtocolNeed::Udp => {
                push_line(profile, "  network inet dgram,");
                push_line(profile, "  network inet6 dgram,");
            }
        }
    }
}

fn push_unix_socket_rules(profile: &mut String, sockets: &[UnixSocketNeed]) {
    for (index, socket) in sockets.iter().enumerate() {
        push_line(profile, "");
        match socket.role {
            UnixSocketRole::Server => {
                push_line(
                    profile,
                    &format!(
                        "  # Unix socket[{index}]: create and use server socket {}.",
                        socket.path
                    ),
                );
                push_line(
                    profile,
                    &format!(
                        "  unix (create, bind, listen, accept, send, receive) type=stream addr={},",
                        quoted(&socket.path)
                    ),
                );
            }
            UnixSocketRole::Client => {
                push_line(
                    profile,
                    &format!(
                        "  # Unix socket[{index}]: connect to client socket {}.",
                        socket.path
                    ),
                );
                push_line(
                    profile,
                    &format!(
                        "  unix (connect, send, receive) type=stream peer=(addr={}),",
                        quoted(&socket.path)
                    ),
                );
            }
        }
        push_line(profile, &format!("  {} rw,", apparmor_path(&socket.path)));
    }
}

fn push_dbus_rules(profile: &mut String, ir: &PolicyIr) {
    for (index, name) in ir.dbus_ownership.iter().enumerate() {
        push_line(profile, "");
        push_line(
            profile,
            &format!(
                "  # D-Bus ownership[{index}]: own {} bus name {}.",
                name.bus, name.name
            ),
        );
        push_line(
            profile,
            &format!("  dbus bind bus={} name={},", name.bus, quoted(&name.name)),
        );
    }

    for (index, name) in ir.dbus_communication.iter().enumerate() {
        push_line(profile, "");
        push_line(
            profile,
            &format!(
                "  # D-Bus communication[{index}]: talk to {} bus service {}.",
                name.bus, name.name
            ),
        );
        push_line(
            profile,
            &format!(
                "  dbus send bus={} peer=(name={}),",
                name.bus,
                quoted(&name.name)
            ),
        );
        push_line(
            profile,
            &format!(
                "  dbus receive bus={} peer=(name={}),",
                name.bus,
                quoted(&name.name)
            ),
        );
    }
}

fn push_capability_rules(profile: &mut String, ir: &PolicyIr) {
    for (index, capability) in ir.capabilities.iter().enumerate() {
        push_line(profile, "");
        push_line(
            profile,
            &format!(
                "  # capabilities[{index}]: Linux capability {}.",
                capability.name
            ),
        );
        push_line(profile, &format!("  capability {},", capability.linux_name));
    }
}

fn push_manual_rules(profile: &mut String, fragments: &[String]) {
    if fragments.is_empty() {
        return;
    }

    push_line(profile, "");
    push_line(profile, "  # Manual AppArmor rule extensions.");
    push_line(
        profile,
        "  # These rules came from extensions.apparmor.rules and should be temporary until Intent has native support.",
    );

    for (index, fragment) in fragments.iter().enumerate() {
        push_line(profile, "");
        push_line(
            profile,
            &format!("  # extensions.apparmor.rules[{index}]: manual policy."),
        );

        for line in fragment.trim().lines() {
            if line.trim().is_empty() {
                push_line(profile, "");
            } else {
                push_line(profile, &format!("  {}", line.trim_start()));
            }
        }
    }
}

fn profile_name(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || matches!(ch, '_' | '-' | '.') {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn protocol_name(protocol: NetworkProtocolNeed) -> &'static str {
    protocol.as_str()
}

fn apparmor_path(path: &str) -> String {
    if path
        .chars()
        .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '/' | '.' | '_' | '-' | '*'))
    {
        path.to_string()
    } else {
        quoted(path)
    }
}

fn quoted(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn trim_trailing_slashes(path: &str) -> String {
    if path == "/" {
        path.to_string()
    } else {
        path.trim_end_matches('/').to_string()
    }
}

fn storage_paths(ir: &PolicyIr, purpose: PathPurpose) -> Vec<&PathNeed> {
    ir.read_only_paths
        .iter()
        .chain(ir.read_write_paths.iter())
        .chain(ir.runtime_paths.iter())
        .filter(|path| path.purpose == purpose)
        .collect()
}

fn push_line(buffer: &mut String, line: &str) {
    buffer.push_str(line);
    buffer.push('\n');
}
