//! SELinux policy generation.

use crate::schema::{
    IntentDocument, NetworkProtocol, StorageAccess, StoragePath, UnixSocket, UnixSocketMode,
};

/// Generate an SELinux type enforcement policy module from an Intent document.
pub fn compile(document: &IntentDocument) -> String {
    let names = Names::new(document);
    let mut policy = String::new();

    push_line(&mut policy, "# Generated by Intent. Do not edit directly.");
    push_line(
        &mut policy,
        "# Edit intent.yaml and regenerate this policy module.",
    );
    push_line(
        &mut policy,
        "# Review generated SELinux policy before loading it.",
    );
    push_line(
        &mut policy,
        &format!("policy_module({}, 1.0)", names.module),
    );
    push_line(&mut policy, "");

    push_type_declarations(&mut policy, document, &names);
    push_domain_rules(&mut policy, document, &names);
    push_storage_rules(
        &mut policy,
        "storage.config",
        &document.storage.config,
        &names,
    );
    push_storage_rules(
        &mut policy,
        "storage.cache",
        &document.storage.cache,
        &names,
    );
    push_storage_rules(
        &mut policy,
        "storage.state",
        &document.storage.state,
        &names,
    );
    push_storage_rules(
        &mut policy,
        "storage.runtime",
        &document.storage.runtime,
        &names,
    );
    push_network_rules(&mut policy, document, &names);
    push_unix_socket_rules(&mut policy, &document.ipc.unix_sockets, &names);
    push_dbus_warnings(&mut policy, document);
    push_capability_rules(&mut policy, document, &names);

    policy
}

/// Generate suggested SELinux file contexts for an Intent document.
pub fn file_contexts(document: &IntentDocument) -> String {
    let names = Names::new(document);
    let mut contexts = String::new();

    push_line(
        &mut contexts,
        "# Generated by Intent. Do not edit directly.",
    );
    push_line(
        &mut contexts,
        "# Suggested SELinux file contexts. Review before installing.",
    );
    push_line(&mut contexts, "");
    push_line(
        &mut contexts,
        "# application.executable: executable entry point.",
    );
    push_line(
        &mut contexts,
        &format!(
            "{} -- gen_context(system_u:object_r:{},s0)",
            file_context_regex(&document.application.executable),
            names.exec_type
        ),
    );

    push_storage_contexts(
        &mut contexts,
        "storage.config",
        &document.storage.config,
        &names.config_type,
    );
    push_storage_contexts(
        &mut contexts,
        "storage.cache",
        &document.storage.cache,
        &names.cache_type,
    );
    push_storage_contexts(
        &mut contexts,
        "storage.state",
        &document.storage.state,
        &names.state_type,
    );
    push_storage_contexts(
        &mut contexts,
        "storage.runtime",
        &document.storage.runtime,
        &names.runtime_type,
    );
    push_socket_contexts(&mut contexts, &document.ipc.unix_sockets, &names);

    contexts
}

/// Return the default `.te` file name for a generated SELinux module.
pub fn module_file_name(document: &IntentDocument) -> String {
    format!("{}.te", module_name(&document.application.name))
}

/// Return the default `.fc` file name for generated SELinux file contexts.
pub fn file_contexts_file_name(document: &IntentDocument) -> String {
    format!("{}.fc", module_name(&document.application.name))
}

fn push_type_declarations(policy: &mut String, document: &IntentDocument, names: &Names) {
    push_line(policy, "########################################");
    push_line(policy, "# Types");
    push_line(policy, "");
    push_line(policy, &format!("type {};", names.domain_type));
    push_line(policy, &format!("type {};", names.exec_type));
    push_line(policy, &format!("files_type({})", names.exec_type));
    push_line(policy, &format!("domain_type({})", names.domain_type));
    push_line(
        policy,
        &format!(
            "domain_entry_file({}, {})",
            names.domain_type, names.exec_type
        ),
    );

    push_storage_type(
        policy,
        &names.config_type,
        !document.storage.config.is_empty(),
        false,
    );
    push_storage_type(
        policy,
        &names.cache_type,
        !document.storage.cache.is_empty(),
        false,
    );
    push_storage_type(
        policy,
        &names.state_type,
        !document.storage.state.is_empty(),
        false,
    );
    push_storage_type(
        policy,
        &names.runtime_type,
        !document.storage.runtime.is_empty() || has_server_socket(&document.ipc.unix_sockets),
        true,
    );
}

fn push_storage_type(policy: &mut String, type_name: &str, needed: bool, runtime: bool) {
    if !needed {
        return;
    }

    push_line(policy, "");
    push_line(policy, &format!("type {type_name};"));
    if runtime {
        push_line(policy, &format!("files_pid_file({type_name})"));
    } else {
        push_line(policy, &format!("files_type({type_name})"));
    }
}

fn push_domain_rules(policy: &mut String, document: &IntentDocument, names: &Names) {
    push_line(policy, "");
    push_line(policy, "########################################");
    push_line(policy, "# Domain");
    push_line(policy, "");
    push_line(
        policy,
        "# application.executable: run the executable as this SELinux domain.",
    );
    push_line(
        policy,
        &format!(
            "init_daemon_domain({}, {})",
            names.domain_type, names.exec_type
        ),
    );

    if document
        .application
        .user
        .as_deref()
        .is_some_and(|user| user != "root")
    {
        push_line(policy, "");
        push_line(
            policy,
            "# WARNING: application.user is not root. SELinux user/domain transitions are distro-specific and were not generated.",
        );
    }
}

fn push_storage_rules(policy: &mut String, field: &str, paths: &[StoragePath], names: &Names) {
    let type_name = match field {
        "storage.config" => &names.config_type,
        "storage.cache" => &names.cache_type,
        "storage.state" => &names.state_type,
        "storage.runtime" => &names.runtime_type,
        _ => unreachable!("unknown storage field"),
    };

    for (index, entry) in paths.iter().enumerate() {
        let access = match entry.access {
            StorageAccess::Read => "read",
            StorageAccess::ReadWrite => "read-write",
        };

        push_line(policy, "");
        push_line(
            policy,
            &format!("# {field}[{index}]: {access} access to {}.", entry.path),
        );

        match entry.access {
            StorageAccess::Read => {
                push_line(
                    policy,
                    &format!(
                        "allow {} {type_name}:dir {{ getattr open read search }};",
                        names.domain_type
                    ),
                );
                push_line(
                    policy,
                    &format!(
                        "allow {} {type_name}:file {{ getattr open read }};",
                        names.domain_type
                    ),
                );
                push_line(
                    policy,
                    &format!(
                        "allow {} {type_name}:lnk_file {{ getattr read }};",
                        names.domain_type
                    ),
                );
            }
            StorageAccess::ReadWrite => {
                push_line(
                    policy,
                    &format!(
                        "allow {} {type_name}:dir {{ add_name create getattr open read remove_name search setattr write }};",
                        names.domain_type
                    ),
                );
                push_line(
                    policy,
                    &format!(
                        "allow {} {type_name}:file {{ append create getattr ioctl lock open read rename setattr unlink write }};",
                        names.domain_type
                    ),
                );
                push_line(
                    policy,
                    &format!(
                        "allow {} {type_name}:lnk_file {{ create getattr read rename setattr unlink }};",
                        names.domain_type
                    ),
                );
            }
        }
    }
}

fn push_network_rules(policy: &mut String, document: &IntentDocument, names: &Names) {
    for (index, outbound) in document.network.outbound.iter().enumerate() {
        push_line(policy, "");
        push_line(
            policy,
            &format!(
                "# network.outbound[{index}]: outbound {} connection to {}{}.",
                protocol_name(outbound.protocol),
                outbound.to,
                outbound
                    .port
                    .map(|port| format!(":{port}"))
                    .unwrap_or_default()
            ),
        );
        push_line(
            policy,
            "# WARNING: SELinux cannot restrict this rule to a DNS name; review the destination and port type.",
        );

        match outbound.protocol {
            NetworkProtocol::Https => {
                push_line(
                    policy,
                    &format!(
                        "allow {} self:tcp_socket {{ connect create getattr getopt read setopt write }};",
                        names.domain_type
                    ),
                );
                push_line(
                    policy,
                    &format!("corenet_tcp_connect_http_port({})", names.domain_type),
                );
            }
            NetworkProtocol::Http => {
                push_line(
                    policy,
                    &format!(
                        "allow {} self:tcp_socket {{ connect create getattr getopt read setopt write }};",
                        names.domain_type
                    ),
                );
                push_line(
                    policy,
                    &format!("corenet_tcp_connect_http_port({})", names.domain_type),
                );
            }
            NetworkProtocol::Tcp => {
                push_line(
                    policy,
                    &format!(
                        "# WARNING: raw TCP port {} has no SELinux port-type mapping in Intent yet.",
                        outbound.port.unwrap_or_default()
                    ),
                );
            }
            NetworkProtocol::Udp => {
                push_line(
                    policy,
                    &format!(
                        "# WARNING: raw UDP port {} has no SELinux port-type mapping in Intent yet.",
                        outbound.port.unwrap_or_default()
                    ),
                );
            }
        }
    }
}

fn push_unix_socket_rules(policy: &mut String, sockets: &[UnixSocket], names: &Names) {
    for (index, socket) in sockets.iter().enumerate() {
        push_line(policy, "");
        match socket.mode {
            UnixSocketMode::Server => {
                push_line(
                    policy,
                    &format!(
                        "# ipc.unix_sockets[{index}]: create and serve Unix stream socket {}.",
                        socket.path
                    ),
                );
                push_line(
                    policy,
                    &format!(
                        "allow {} self:unix_stream_socket {{ accept bind create getattr getopt listen read setopt write }};",
                        names.domain_type
                    ),
                );
                push_line(
                    policy,
                    &format!(
                        "allow {} {}:sock_file {{ create getattr setattr unlink write }};",
                        names.domain_type, names.runtime_type
                    ),
                );
            }
            UnixSocketMode::Client => {
                push_line(
                    policy,
                    &format!(
                        "# ipc.unix_sockets[{index}]: connect to Unix stream socket {}.",
                        socket.path
                    ),
                );
                push_line(
                    policy,
                    "# WARNING: peer socket label is not known from the current intent schema; add a site-specific allow rule for the peer type.",
                );
                push_line(
                    policy,
                    &format!(
                        "allow {} self:unix_stream_socket {{ connect create getattr getopt read setopt write }};",
                        names.domain_type
                    ),
                );
            }
        }
    }
}

fn push_dbus_warnings(policy: &mut String, document: &IntentDocument) {
    for (index, name) in document.ipc.dbus.system.owns.iter().enumerate() {
        push_line(policy, "");
        push_line(
            policy,
            &format!(
                "# WARNING: ipc.dbus.system.owns[{index}] ({name}) requires distro-specific D-Bus SELinux policy and was not generated."
            ),
        );
    }

    for (index, name) in document.ipc.dbus.system.talks_to.iter().enumerate() {
        push_line(policy, "");
        push_line(
            policy,
            &format!(
                "# WARNING: ipc.dbus.system.talks_to[{index}] ({name}) requires peer service types and was not generated."
            ),
        );
    }
}

fn push_capability_rules(policy: &mut String, document: &IntentDocument, names: &Names) {
    for (index, capability) in document.capabilities.iter().enumerate() {
        let capability = capability.replace('-', "_");

        push_line(policy, "");
        push_line(
            policy,
            &format!("# capabilities[{index}]: Linux capability {capability}."),
        );
        push_line(
            policy,
            &format!("allow {} self:capability {capability};", names.domain_type),
        );
    }
}

fn push_storage_contexts(
    contexts: &mut String,
    field: &str,
    paths: &[StoragePath],
    type_name: &str,
) {
    for (index, entry) in paths.iter().enumerate() {
        push_line(contexts, "");
        push_line(
            contexts,
            &format!("# {field}[{index}]: label {}.", entry.path),
        );
        push_line(
            contexts,
            &format!(
                "{}(/.*)? gen_context(system_u:object_r:{type_name},s0)",
                file_context_regex(trim_trailing_slashes(&entry.path).as_str())
            ),
        );
    }
}

fn push_socket_contexts(contexts: &mut String, sockets: &[UnixSocket], names: &Names) {
    for (index, socket) in sockets.iter().enumerate() {
        push_line(contexts, "");
        match socket.mode {
            UnixSocketMode::Server => {
                push_line(
                    contexts,
                    &format!(
                        "# ipc.unix_sockets[{index}]: label server socket {}.",
                        socket.path
                    ),
                );
                push_line(
                    contexts,
                    &format!(
                        "{} -s gen_context(system_u:object_r:{},s0)",
                        file_context_regex(&socket.path),
                        names.runtime_type
                    ),
                );
            }
            UnixSocketMode::Client => {
                push_line(
                    contexts,
                    &format!(
                        "# WARNING: ipc.unix_sockets[{index}] is a client socket; Intent will not relabel peer-owned path {}.",
                        socket.path
                    ),
                );
            }
        }
    }
}

fn has_server_socket(sockets: &[UnixSocket]) -> bool {
    sockets
        .iter()
        .any(|socket| socket.mode == UnixSocketMode::Server)
}

fn protocol_name(protocol: NetworkProtocol) -> &'static str {
    match protocol {
        NetworkProtocol::Http => "http",
        NetworkProtocol::Https => "https",
        NetworkProtocol::Tcp => "tcp",
        NetworkProtocol::Udp => "udp",
    }
}

fn module_name(name: &str) -> String {
    let mut module = String::new();

    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            module.push(ch.to_ascii_lowercase());
        } else if ch == '_' {
            module.push(ch);
        } else {
            module.push('_');
        }
    }

    while module.contains("__") {
        module = module.replace("__", "_");
    }

    module = module.trim_matches('_').to_string();

    if module.is_empty() {
        return "intent_app".to_string();
    }

    if module.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        module.insert_str(0, "intent_");
    }

    module
}

fn file_context_regex(path: &str) -> String {
    path.chars()
        .flat_map(|ch| match ch {
            '.' | '+' | '?' | '*' | '^' | '$' | '(' | ')' | '[' | ']' | '{' | '}' | '|' | '\\' => {
                ['\\', ch]
            }
            ' ' => ['\\', ' '],
            _ => ['\0', ch],
        })
        .filter(|ch| *ch != '\0')
        .collect()
}

fn trim_trailing_slashes(path: &str) -> String {
    if path == "/" {
        path.to_string()
    } else {
        path.trim_end_matches('/').to_string()
    }
}

fn push_line(buffer: &mut String, line: &str) {
    buffer.push_str(line);
    buffer.push('\n');
}

struct Names {
    module: String,
    domain_type: String,
    exec_type: String,
    config_type: String,
    cache_type: String,
    state_type: String,
    runtime_type: String,
}

impl Names {
    fn new(document: &IntentDocument) -> Self {
        let module = module_name(&document.application.name);

        Self {
            domain_type: format!("{module}_t"),
            exec_type: format!("{module}_exec_t"),
            config_type: format!("{module}_config_t"),
            cache_type: format!("{module}_cache_t"),
            state_type: format!("{module}_state_t"),
            runtime_type: format!("{module}_runtime_t"),
            module,
        }
    }
}
