//! SELinux policy generation.

use crate::ir::{
    NetworkProtocolNeed, PathAccess, PathNeed, PathPurpose, PolicyIr, UnixSocketNeed,
    UnixSocketRole,
};

/// Generate an SELinux type enforcement policy module from normalized policy intent.
pub fn compile(ir: &PolicyIr) -> String {
    let names = Names::new(ir);
    let mut policy = String::new();

    push_line(&mut policy, "# Generated by Intent. Do not edit directly.");
    push_line(
        &mut policy,
        "# Edit intent.yaml and regenerate this policy module.",
    );
    push_line(
        &mut policy,
        "# Review generated SELinux policy before loading it.",
    );
    push_line(
        &mut policy,
        &format!("policy_module({}, 1.0)", names.module),
    );
    push_line(&mut policy, "");

    push_type_declarations(&mut policy, ir, &names);
    push_domain_rules(&mut policy, ir, &names);
    push_storage_rules(
        &mut policy,
        PathPurpose::Config,
        &storage_paths(ir, PathPurpose::Config),
        &names,
    );
    push_storage_rules(
        &mut policy,
        PathPurpose::Cache,
        &storage_paths(ir, PathPurpose::Cache),
        &names,
    );
    push_storage_rules(
        &mut policy,
        PathPurpose::State,
        &storage_paths(ir, PathPurpose::State),
        &names,
    );
    push_storage_rules(
        &mut policy,
        PathPurpose::Runtime,
        &storage_paths(ir, PathPurpose::Runtime),
        &names,
    );
    push_network_rules(&mut policy, &ir.outbound_network, &names);
    push_unix_socket_rules(&mut policy, &ir.unix_sockets, &names);
    push_dbus_warnings(&mut policy, ir);
    push_capability_rules(&mut policy, ir, &names);

    policy
}

/// Generate suggested SELinux file contexts for normalized policy intent.
pub fn file_contexts(ir: &PolicyIr) -> String {
    let names = Names::new(ir);
    let mut contexts = String::new();

    push_line(
        &mut contexts,
        "# Generated by Intent. Do not edit directly.",
    );
    push_line(
        &mut contexts,
        "# Suggested SELinux file contexts. Review before installing.",
    );
    push_line(&mut contexts, "");
    push_line(
        &mut contexts,
        "# application.executable: executable entry point.",
    );
    push_line(
        &mut contexts,
        &format!(
            "{} -- gen_context(system_u:object_r:{},s0)",
            file_context_regex(&ir.application.executable),
            names.exec_type
        ),
    );

    push_storage_contexts(
        &mut contexts,
        PathPurpose::Config,
        &storage_paths(ir, PathPurpose::Config),
        &names.config_type,
    );
    push_storage_contexts(
        &mut contexts,
        PathPurpose::Cache,
        &storage_paths(ir, PathPurpose::Cache),
        &names.cache_type,
    );
    push_storage_contexts(
        &mut contexts,
        PathPurpose::State,
        &storage_paths(ir, PathPurpose::State),
        &names.state_type,
    );
    push_storage_contexts(
        &mut contexts,
        PathPurpose::Runtime,
        &storage_paths(ir, PathPurpose::Runtime),
        &names.runtime_type,
    );
    push_socket_contexts(&mut contexts, &ir.unix_sockets, &names);

    contexts
}

/// Return the default `.te` file name for a generated SELinux module.
pub fn module_file_name(ir: &PolicyIr) -> String {
    format!("{}.te", module_name(&ir.application.name))
}

/// Return the default `.fc` file name for generated SELinux file contexts.
pub fn file_contexts_file_name(ir: &PolicyIr) -> String {
    format!("{}.fc", module_name(&ir.application.name))
}

fn push_type_declarations(policy: &mut String, ir: &PolicyIr, names: &Names) {
    push_line(policy, "########################################");
    push_line(policy, "# Types");
    push_line(policy, "");
    push_line(policy, &format!("type {};", names.domain_type));
    push_line(policy, &format!("type {};", names.exec_type));
    push_line(policy, &format!("files_type({})", names.exec_type));
    push_line(policy, &format!("domain_type({})", names.domain_type));
    push_line(
        policy,
        &format!(
            "domain_entry_file({}, {})",
            names.domain_type, names.exec_type
        ),
    );

    push_storage_type(
        policy,
        &names.config_type,
        has_storage_path(ir, PathPurpose::Config),
        false,
    );
    push_storage_type(
        policy,
        &names.cache_type,
        has_storage_path(ir, PathPurpose::Cache),
        false,
    );
    push_storage_type(
        policy,
        &names.state_type,
        has_storage_path(ir, PathPurpose::State),
        false,
    );
    push_storage_type(
        policy,
        &names.runtime_type,
        has_storage_path(ir, PathPurpose::Runtime) || has_server_socket(&ir.unix_sockets),
        true,
    );
}

fn push_storage_type(policy: &mut String, type_name: &str, needed: bool, runtime: bool) {
    if !needed {
        return;
    }

    push_line(policy, "");
    push_line(policy, &format!("type {type_name};"));
    if runtime {
        push_line(policy, &format!("files_pid_file({type_name})"));
    } else {
        push_line(policy, &format!("files_type({type_name})"));
    }
}

fn push_domain_rules(policy: &mut String, ir: &PolicyIr, names: &Names) {
    push_line(policy, "");
    push_line(policy, "########################################");
    push_line(policy, "# Domain");
    push_line(policy, "");
    push_line(
        policy,
        "# application.executable: run the executable as this SELinux domain.",
    );
    push_line(
        policy,
        &format!(
            "init_daemon_domain({}, {})",
            names.domain_type, names.exec_type
        ),
    );

    if ir
        .application
        .user
        .as_deref()
        .is_some_and(|user| user != "root")
    {
        push_line(policy, "");
        push_line(
            policy,
            "# WARNING: application.user is not root. SELinux user/domain transitions are distro-specific and were not generated.",
        );
    }
}

fn push_storage_rules(
    policy: &mut String,
    purpose: PathPurpose,
    paths: &[&PathNeed],
    names: &Names,
) {
    let type_name = match purpose {
        PathPurpose::Config => &names.config_type,
        PathPurpose::Cache => &names.cache_type,
        PathPurpose::State => &names.state_type,
        PathPurpose::Runtime => &names.runtime_type,
    };

    for (index, entry) in paths.iter().enumerate() {
        push_line(policy, "");
        push_line(
            policy,
            &format!(
                "# {} paths[{index}]: {} access to {}.",
                purpose, entry.access, entry.path
            ),
        );

        match entry.access {
            PathAccess::Read => {
                push_line(
                    policy,
                    &format!(
                        "allow {} {type_name}:dir {{ getattr open read search }};",
                        names.domain_type
                    ),
                );
                push_line(
                    policy,
                    &format!(
                        "allow {} {type_name}:file {{ getattr open read }};",
                        names.domain_type
                    ),
                );
                push_line(
                    policy,
                    &format!(
                        "allow {} {type_name}:lnk_file {{ getattr read }};",
                        names.domain_type
                    ),
                );
            }
            PathAccess::ReadWrite => {
                push_line(
                    policy,
                    &format!(
                        "allow {} {type_name}:dir {{ add_name create getattr open read remove_name search setattr write }};",
                        names.domain_type
                    ),
                );
                push_line(
                    policy,
                    &format!(
                        "allow {} {type_name}:file {{ append create getattr ioctl lock open read rename setattr unlink write }};",
                        names.domain_type
                    ),
                );
                push_line(
                    policy,
                    &format!(
                        "allow {} {type_name}:lnk_file {{ create getattr read rename setattr unlink }};",
                        names.domain_type
                    ),
                );
            }
        }
    }
}

fn push_network_rules(
    policy: &mut String,
    outbound: &[crate::ir::OutboundNetworkNeed],
    names: &Names,
) {
    for (index, outbound) in outbound.iter().enumerate() {
        push_line(policy, "");
        push_line(
            policy,
            &format!(
                "# outbound network[{index}]: outbound {} connection to {}:{}.",
                protocol_name(outbound.protocol),
                outbound.to,
                outbound.port
            ),
        );
        push_line(
            policy,
            "# WARNING: SELinux cannot restrict this rule to a DNS name; review the destination and port type.",
        );

        match outbound.protocol {
            NetworkProtocolNeed::Https => {
                push_line(
                    policy,
                    &format!(
                        "allow {} self:tcp_socket {{ connect create getattr getopt read setopt write }};",
                        names.domain_type
                    ),
                );
                push_line(
                    policy,
                    &format!("corenet_tcp_connect_http_port({})", names.domain_type),
                );
            }
            NetworkProtocolNeed::Http => {
                push_line(
                    policy,
                    &format!(
                        "allow {} self:tcp_socket {{ connect create getattr getopt read setopt write }};",
                        names.domain_type
                    ),
                );
                push_line(
                    policy,
                    &format!("corenet_tcp_connect_http_port({})", names.domain_type),
                );
            }
            NetworkProtocolNeed::Tcp => {
                push_line(
                    policy,
                    &format!(
                        "# WARNING: raw TCP port {} has no SELinux port-type mapping in Intent yet.",
                        outbound.port
                    ),
                );
            }
            NetworkProtocolNeed::Udp => {
                push_line(
                    policy,
                    &format!(
                        "# WARNING: raw UDP port {} has no SELinux port-type mapping in Intent yet.",
                        outbound.port
                    ),
                );
            }
        }
    }
}

fn push_unix_socket_rules(policy: &mut String, sockets: &[UnixSocketNeed], names: &Names) {
    for (index, socket) in sockets.iter().enumerate() {
        push_line(policy, "");
        match socket.role {
            UnixSocketRole::Server => {
                push_line(
                    policy,
                    &format!(
                        "# Unix socket[{index}]: create and serve Unix stream socket {}.",
                        socket.path
                    ),
                );
                push_line(
                    policy,
                    &format!(
                        "allow {} self:unix_stream_socket {{ accept bind create getattr getopt listen read setopt write }};",
                        names.domain_type
                    ),
                );
                push_line(
                    policy,
                    &format!(
                        "allow {} {}:sock_file {{ create getattr setattr unlink write }};",
                        names.domain_type, names.runtime_type
                    ),
                );
            }
            UnixSocketRole::Client => {
                push_line(
                    policy,
                    &format!(
                        "# Unix socket[{index}]: connect to Unix stream socket {}.",
                        socket.path
                    ),
                );
                push_line(
                    policy,
                    "# WARNING: peer socket label is not known from the current intent schema; add a site-specific allow rule for the peer type.",
                );
                push_line(
                    policy,
                    &format!(
                        "allow {} self:unix_stream_socket {{ connect create getattr getopt read setopt write }};",
                        names.domain_type
                    ),
                );
            }
        }
    }
}

fn push_dbus_warnings(policy: &mut String, ir: &PolicyIr) {
    for (index, name) in ir.dbus_ownership.iter().enumerate() {
        push_line(policy, "");
        push_line(
            policy,
            &format!(
                "# WARNING: D-Bus ownership[{index}] ({} bus name {}) requires distro-specific D-Bus SELinux policy and was not generated.",
                name.bus, name.name
            ),
        );
    }

    for (index, name) in ir.dbus_communication.iter().enumerate() {
        push_line(policy, "");
        push_line(
            policy,
            &format!(
                "# WARNING: D-Bus communication[{index}] ({} bus name {}) requires peer service types and was not generated.",
                name.bus, name.name
            ),
        );
    }
}

fn push_capability_rules(policy: &mut String, ir: &PolicyIr, names: &Names) {
    for (index, capability) in ir.capabilities.iter().enumerate() {
        push_line(policy, "");
        push_line(
            policy,
            &format!(
                "# capabilities[{index}]: Linux capability {}.",
                capability.name
            ),
        );
        push_line(
            policy,
            &format!(
                "allow {} self:capability {};",
                names.domain_type, capability.linux_name
            ),
        );
    }
}

fn push_storage_contexts(
    contexts: &mut String,
    purpose: PathPurpose,
    paths: &[&PathNeed],
    type_name: &str,
) {
    for (index, entry) in paths.iter().enumerate() {
        push_line(contexts, "");
        push_line(
            contexts,
            &format!("# {} paths[{index}]: label {}.", purpose, entry.path),
        );
        push_line(
            contexts,
            &format!(
                "{}(/.*)? gen_context(system_u:object_r:{type_name},s0)",
                file_context_regex(trim_trailing_slashes(&entry.path).as_str())
            ),
        );
    }
}

fn push_socket_contexts(contexts: &mut String, sockets: &[UnixSocketNeed], names: &Names) {
    for (index, socket) in sockets.iter().enumerate() {
        push_line(contexts, "");
        match socket.role {
            UnixSocketRole::Server => {
                push_line(
                    contexts,
                    &format!(
                        "# Unix socket[{index}]: label server socket {}.",
                        socket.path
                    ),
                );
                push_line(
                    contexts,
                    &format!(
                        "{} -s gen_context(system_u:object_r:{},s0)",
                        file_context_regex(&socket.path),
                        names.runtime_type
                    ),
                );
            }
            UnixSocketRole::Client => {
                push_line(
                    contexts,
                    &format!(
                        "# WARNING: Unix socket[{index}] is a client socket; Intent will not relabel peer-owned path {}.",
                        socket.path
                    ),
                );
            }
        }
    }
}

fn has_server_socket(sockets: &[UnixSocketNeed]) -> bool {
    sockets
        .iter()
        .any(|socket| socket.role == UnixSocketRole::Server)
}

fn protocol_name(protocol: NetworkProtocolNeed) -> &'static str {
    protocol.as_str()
}

fn module_name(name: &str) -> String {
    let mut module = String::new();

    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            module.push(ch.to_ascii_lowercase());
        } else if ch == '_' {
            module.push(ch);
        } else {
            module.push('_');
        }
    }

    while module.contains("__") {
        module = module.replace("__", "_");
    }

    module = module.trim_matches('_').to_string();

    if module.is_empty() {
        return "intent_app".to_string();
    }

    if module.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        module.insert_str(0, "intent_");
    }

    module
}

fn file_context_regex(path: &str) -> String {
    path.chars()
        .flat_map(|ch| match ch {
            '.' | '+' | '?' | '*' | '^' | '$' | '(' | ')' | '[' | ']' | '{' | '}' | '|' | '\\' => {
                ['\\', ch]
            }
            ' ' => ['\\', ' '],
            _ => ['\0', ch],
        })
        .filter(|ch| *ch != '\0')
        .collect()
}

fn trim_trailing_slashes(path: &str) -> String {
    if path == "/" {
        path.to_string()
    } else {
        path.trim_end_matches('/').to_string()
    }
}

fn storage_paths(ir: &PolicyIr, purpose: PathPurpose) -> Vec<&PathNeed> {
    ir.read_only_paths
        .iter()
        .chain(ir.read_write_paths.iter())
        .chain(ir.runtime_paths.iter())
        .filter(|path| path.purpose == purpose)
        .collect()
}

fn has_storage_path(ir: &PolicyIr, purpose: PathPurpose) -> bool {
    ir.read_only_paths
        .iter()
        .chain(ir.read_write_paths.iter())
        .chain(ir.runtime_paths.iter())
        .any(|path| path.purpose == purpose)
}

fn push_line(buffer: &mut String, line: &str) {
    buffer.push_str(line);
    buffer.push('\n');
}

struct Names {
    module: String,
    domain_type: String,
    exec_type: String,
    config_type: String,
    cache_type: String,
    state_type: String,
    runtime_type: String,
}

impl Names {
    fn new(ir: &PolicyIr) -> Self {
        let module = module_name(&ir.application.name);

        Self {
            domain_type: format!("{module}_t"),
            exec_type: format!("{module}_exec_t"),
            config_type: format!("{module}_config_t"),
            cache_type: format!("{module}_cache_t"),
            state_type: format!("{module}_state_t"),
            runtime_type: format!("{module}_runtime_t"),
            module,
        }
    }
}
