//! systemd service hardening drop-in suggestions.

use crate::ir::{NetworkProtocolNeed, PathAccess, PathNeed, PathPurpose, PolicyIr, UnixSocketNeed};

/// Generate advisory systemd service hardening from normalized policy intent.
pub fn compile(ir: &PolicyIr) -> String {
    let mut dropin = String::new();

    push_line(&mut dropin, "# Generated by Intent. Do not edit directly.");
    push_line(
        &mut dropin,
        "# Advisory systemd service hardening. Review before installing as a drop-in.",
    );
    push_line(
        &mut dropin,
        "# This complements SELinux/AppArmor policy; it is not a complete unit file.",
    );
    push_line(&mut dropin, "[Service]");

    push_directory_suggestions(&mut dropin, ir);
    push_path_suggestions(&mut dropin, ir);
    push_privilege_suggestions(&mut dropin, ir);
    push_namespace_suggestions(&mut dropin, ir);
    push_network_suggestions(&mut dropin, ir);

    dropin
}

/// Return the default systemd drop-in file name.
pub fn dropin_file_name() -> String {
    "10-intent-hardening.conf".to_string()
}

fn push_directory_suggestions(dropin: &mut String, ir: &PolicyIr) {
    let runtime = directory_names(ir, PathPurpose::Runtime, "/run/");
    if runtime.is_empty() && has_writable_paths_for_purpose(ir, PathPurpose::Runtime) {
        push_line(dropin, "");
        push_line(
            dropin,
            "# RuntimeDirectory= was not generated because writable runtime paths are outside /run or are not safe directory names.",
        );
    } else if !runtime.is_empty() {
        push_line(dropin, "");
        push_line(
            dropin,
            "# runtime storage: create service-owned directories under /run.",
        );
        push_line(dropin, &format!("RuntimeDirectory={}", runtime.join(" ")));
    }

    let cache = directory_names(ir, PathPurpose::Cache, "/var/cache/");
    if cache.is_empty() && has_writable_paths_for_purpose(ir, PathPurpose::Cache) {
        push_line(dropin, "");
        push_line(
            dropin,
            "# CacheDirectory= was not generated because writable cache paths are outside /var/cache or are not safe directory names.",
        );
    } else if !cache.is_empty() {
        push_line(dropin, "");
        push_line(
            dropin,
            "# cache storage: create service-owned directories under /var/cache.",
        );
        push_line(dropin, &format!("CacheDirectory={}", cache.join(" ")));
    }

    let state = directory_names(ir, PathPurpose::State, "/var/lib/");
    if state.is_empty() && has_writable_paths_for_purpose(ir, PathPurpose::State) {
        push_line(dropin, "");
        push_line(
            dropin,
            "# StateDirectory= was not generated because writable state paths are outside /var/lib or are not safe directory names.",
        );
    } else if !state.is_empty() {
        push_line(dropin, "");
        push_line(
            dropin,
            "# state storage: create service-owned directories under /var/lib.",
        );
        push_line(dropin, &format!("StateDirectory={}", state.join(" ")));
    }
}

fn push_path_suggestions(dropin: &mut String, ir: &PolicyIr) {
    if !ir.read_only_paths.is_empty() {
        push_line(dropin, "");
        push_line(dropin, "# declared read-only storage.");
        push_line(
            dropin,
            &format!(
                "ReadOnlyPaths={}",
                join_paths(ir.read_only_paths.iter().map(|path| path.path.as_str()))
            ),
        );
    }

    let read_write = ir
        .read_write_paths
        .iter()
        .chain(ir.runtime_paths.iter())
        .collect::<Vec<_>>();
    if !read_write.is_empty() {
        push_line(dropin, "");
        push_line(
            dropin,
            "# declared writable storage; keep this list narrow when ProtectSystem= is enabled.",
        );
        push_line(
            dropin,
            &format!(
                "ReadWritePaths={}",
                join_paths(read_write.iter().map(|path| path.path.as_str()))
            ),
        );
    }
}

fn push_privilege_suggestions(dropin: &mut String, ir: &PolicyIr) {
    push_line(dropin, "");
    if ir.capabilities.is_empty() {
        push_line(
            dropin,
            "# no Linux capabilities were declared, so block acquiring new privileges.",
        );
        push_line(dropin, "NoNewPrivileges=yes");
    } else {
        push_line(
            dropin,
            "# NoNewPrivileges= was not generated because capabilities were declared and the service may need privilege setup in its unit.",
        );
    }
}

fn push_namespace_suggestions(dropin: &mut String, ir: &PolicyIr) {
    push_line(dropin, "");
    if uses_temp_paths(ir) {
        push_line(
            dropin,
            "# PrivateTmp= was not generated because intent references /tmp or /var/tmp paths.",
        );
    } else {
        push_line(dropin, "# isolate service temporary files.");
        push_line(dropin, "PrivateTmp=yes");
    }

    push_line(dropin, "");
    if has_writable_system_path(ir) {
        push_line(
            dropin,
            "# ProtectSystem= was not generated because intent declares writable paths under /usr, /boot, or /etc.",
        );
    } else {
        push_line(
            dropin,
            "# make the OS image read-only; ReadWritePaths= and systemd directories keep declared storage writable.",
        );
        push_line(dropin, "ProtectSystem=strict");
    }

    push_line(dropin, "");
    match home_access(ir) {
        HomeAccess::None => {
            push_line(dropin, "# no home-directory access was declared.");
            push_line(dropin, "ProtectHome=yes");
        }
        HomeAccess::ReadOnly => {
            push_line(dropin, "# home-directory access was declared read-only.");
            push_line(dropin, "ProtectHome=read-only");
        }
        HomeAccess::ReadWrite => {
            push_line(
                dropin,
                "# ProtectHome= was not generated because intent declares writable home-directory paths.",
            );
        }
    }
}

fn push_network_suggestions(dropin: &mut String, ir: &PolicyIr) {
    let families = address_families(ir);
    push_line(dropin, "");
    if families.is_empty() {
        push_line(
            dropin,
            "# RestrictAddressFamilies= was not generated because no network or IPC address-family needs were declared.",
        );
    } else {
        push_line(
            dropin,
            "# restrict sockets to address families implied by intent.",
        );
        push_line(
            dropin,
            &format!("RestrictAddressFamilies={}", families.join(" ")),
        );
    }
}

fn directory_names(ir: &PolicyIr, purpose: PathPurpose, prefix: &str) -> Vec<String> {
    let mut names = storage_paths(ir, purpose)
        .into_iter()
        .filter(|path| path.access == PathAccess::ReadWrite)
        .filter_map(|path| path.path.strip_prefix(prefix))
        .filter(|name| safe_directory_name(name))
        .map(ToString::to_string)
        .collect::<Vec<_>>();
    names.sort();
    names.dedup();
    names
}

fn storage_paths(ir: &PolicyIr, purpose: PathPurpose) -> Vec<&PathNeed> {
    ir.read_only_paths
        .iter()
        .chain(ir.read_write_paths.iter())
        .chain(ir.runtime_paths.iter())
        .filter(|path| path.purpose == purpose)
        .collect()
}

fn has_writable_paths_for_purpose(ir: &PolicyIr, purpose: PathPurpose) -> bool {
    ir.read_only_paths
        .iter()
        .chain(ir.read_write_paths.iter())
        .chain(ir.runtime_paths.iter())
        .any(|path| path.purpose == purpose && path.access == PathAccess::ReadWrite)
}

fn join_paths<'a>(paths: impl Iterator<Item = &'a str>) -> String {
    paths.map(systemd_path).collect::<Vec<_>>().join(" ")
}

fn systemd_path(path: &str) -> String {
    if path
        .chars()
        .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '/' | '.' | '_' | '-' | ':'))
    {
        path.to_string()
    } else {
        format!("\"{}\"", path.replace('\\', "\\\\").replace('"', "\\\""))
    }
}

fn safe_directory_name(name: &str) -> bool {
    !name.is_empty()
        && !name.starts_with('/')
        && !name.starts_with('-')
        && !name.contains("..")
        && name
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '/' | '.' | '_' | '-'))
}

fn uses_temp_paths(ir: &PolicyIr) -> bool {
    all_paths(ir).any(is_temp_path)
}

fn has_writable_system_path(ir: &PolicyIr) -> bool {
    ir.read_write_paths
        .iter()
        .chain(ir.runtime_paths.iter())
        .any(|path| {
            path.path == "/usr"
                || path.path.starts_with("/usr/")
                || path.path == "/boot"
                || path.path.starts_with("/boot/")
                || path.path == "/etc"
                || path.path.starts_with("/etc/")
        })
}

fn home_access(ir: &PolicyIr) -> HomeAccess {
    if ir
        .read_write_paths
        .iter()
        .chain(ir.runtime_paths.iter())
        .any(|path| is_home_path(&path.path))
    {
        HomeAccess::ReadWrite
    } else if ir
        .read_only_paths
        .iter()
        .any(|path| is_home_path(&path.path))
    {
        HomeAccess::ReadOnly
    } else {
        HomeAccess::None
    }
}

fn address_families(ir: &PolicyIr) -> Vec<&'static str> {
    let mut families = Vec::new();

    if !ir.unix_sockets.is_empty()
        || !ir.dbus_ownership.is_empty()
        || !ir.dbus_communication.is_empty()
    {
        families.push("AF_UNIX");
    }

    if ir.outbound_network.iter().any(|network| {
        matches!(
            network.protocol,
            NetworkProtocolNeed::Http
                | NetworkProtocolNeed::Https
                | NetworkProtocolNeed::Tcp
                | NetworkProtocolNeed::Udp
        )
    }) {
        families.push("AF_INET");
        families.push("AF_INET6");
    }

    families
}

fn all_paths(ir: &PolicyIr) -> impl Iterator<Item = &str> {
    ir.read_only_paths
        .iter()
        .chain(ir.read_write_paths.iter())
        .chain(ir.runtime_paths.iter())
        .map(|path| path.path.as_str())
        .chain(ir.unix_sockets.iter().map(socket_path))
}

fn socket_path(socket: &UnixSocketNeed) -> &str {
    socket.path.as_str()
}

fn is_temp_path(path: &str) -> bool {
    path == "/tmp"
        || path.starts_with("/tmp/")
        || path == "/var/tmp"
        || path.starts_with("/var/tmp/")
}

fn is_home_path(path: &str) -> bool {
    path == "/home" || path.starts_with("/home/") || path == "/root" || path.starts_with("/root/")
}

fn push_line(buffer: &mut String, line: &str) {
    buffer.push_str(line);
    buffer.push('\n');
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum HomeAccess {
    None,
    ReadOnly,
    ReadWrite,
}
